---
- name: restart_step_ca
  ansible.builtin.systemd:
    name: step-ca
    state: restarted
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode

- name: reload_nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    enabled: true
  when: not ansible_check_mode