---
- name: restart_powerdns
  ansible.builtin.systemd:
    name: pdns
    state: restarted
    enabled: true
  when: not ansible_check_mode

- name: restart_pdns_recursor
  ansible.builtin.systemd:
    name: pdns-recursor
    state: restarted
    enabled: true
  when: not ansible_check_mode

- name: restart_nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
  when: not ansible_check_mode