---
- name: K8S | Prepare Linux | Disable swap runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
  tags:
    - prepare_linux

- name: K8S | Prepare Linux | Disable swap persistently in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.*\s+swap\s+.*)$'
    replace: '#\1'
  tags:
    - prepare_linux

- name: K8S | Prepare Linux | Ensure kernel modules are loaded
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay
  tags:
    - prepare_linux

- name: K8S | Prepare Linux | Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      overlay
  tags:
    - prepare_linux

- name: K8S | Prepare Linux | Sysctl rules
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  notify: reload_sysctl
  tags:
    - prepare_linux

- name: K8S | Prepare Linux | Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: yes
  tags:
    - prepare_linux