---
- name: restart_semaphore
  ansible.builtin.systemd:
    name: semaphore
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart_nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes