- name: Outline | Install Nginx | Install Nginx packages
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true
  tags:
    - install
    - upgrade

- name: Outline | Install Nginx | Create site file for Gitlab
  ansible.builtin.template:
    src: outline-nginx.j2
    dest: /etc/nginx/sites-available/outline
    owner: root
    group: root
    mode: '644'
  tags:
    - install
    - update_config

- name: Outline | Install Nginx | Create symlink for site file
  ansible.builtin.file:
    src: /etc/nginx/sites-available/outline
    dest: /etc/nginx/sites-enabled/outline
    state: link
  notify: reload_nginx
  tags:
    - install