---
- name: Install Outline
  ansible.builtin.import_tasks: install_outline.yaml
  tags:
    - install_outline

- name: Install Nginx
  ansible.builtin.import_tasks: install_nginx.yaml
  tags:
    - install_nginx