---
- name: PowerDNS | Install | Install required packages
  ansible.builtin.apt:
    name:
      - pdns-server={{ powerdns.pdns_version }}
      - pdns-backend-pgsql={{ powerdns.pgsql_version }}
    state: present
    update_cache: true
  become: true

- name: PowerDNS | Install | Change Primary DNS
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '^#?nameserver'
    line: 'nameserver {{ powerdns.forwarders.primary }}'
    create: yes

- name: PowerDNS | Install | Create drop-in folder for pdns.service
  ansible.builtin.file:
    path: /etc/systemd/system/pdns.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: PowerDNS | Install | Create Systemd override
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/pdns.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: PowerDNS | Install | Create pdns.conf file
  ansible.builtin.template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
    owner: pdns
    group: pdns
    mode: '0644'
  tags: 
    - update_config

- name: PowerDNS | Install | Create psql.conf file
  ansible.builtin.template:
    src: psql.conf.j2
    dest: /etc/powerdns/pdns.d/psql.conf
    owner: pdns
    group: pdns
    mode: '0644'
  tags: 
    - update_config
  notify: restart_powerdns