- name: Common | Install Vault | Install Hashicorp GPG key
  ansible.builtin.shell: > 
    wget -qO- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg 
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Common | Install Vault | Add HashiCorp repository
  ansible.builtin.template:
    src: hashicorp.list.j2
    dest: /etc/apt/sources.list.d/hashicorp.list
    owner: root
    group: root
    mode: '0644'

- name: Common | Install Vault | Install Vault
  ansible.builtin.apt:
    name: vault
    state: present
    update_cache: yes
