---
- name: Common | Download Enpos CA root certificate
  ansible.builtin.get_url:
    url: "{{ globvar.enpos_root_ca_url }}"
    dest: /usr/local/share/ca-certificates/enpos-root.crt
    mode: '0644'
  tags: common

- name: Common | Update CA certificates
  ansible.builtin.command: update-ca-certificates
  tags: common
  register: common_output
  changed_when: common_output.rc != 0  # Handling execution errors
