- name: Common | Install Vault | Install Hashicorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Common | Install Vault | Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Common | Install Vault | Install Vault
  ansible.builtin.apt:
    name: vault
    state: present
    update_cache: yes
