- name: Authentik | Install Nginx | Install Nginx packages
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true
  tags:
    - install
    - upgrade

- name: Authentik | Install Nginx | Create site file for ACME
  ansible.builtin.template:
    src: authentik-nginx.j2
    dest: /etc/nginx/sites-available/authentik
    owner: root
    group: root
    mode: '644'
  tags:
    - install
    - update

- name: Authentik | Install Nginx | Create symlink for site file
  ansible.builtin.file:
    src: /etc/nginx/sites-available/authentik
    dest: /etc/nginx/sites-enabled/authentik
    state: link
  notify: reload_nginx