- name: Install Authentik
  ansible.builtin.import_tasks: install_authentik.yaml
  tags:
    - install_authentik
- name: Install Nginx
  ansible.builtin.import_tasks: install_nginx.yaml
  tags:
    - install_nginx