---
coredns:
  version: "0.1-0"
  forwarders:
    - 1.1.1.1
    - 8.8.8.8
  db:
    name: "coredns"
    user: "coredns_user"
    password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'postgresql/users')['secret']['coredns_user'] }}"