smtp_relay:
  hostname: "{{ inventory_hostname }}"
  domain: "{{ globvar.domains.external }}"
  smtp:
    username: "{{ lookup('community.hashi_vault.vault_kv2_get', 'smtp_relay')['secret']['username'] }}"
    password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'smtp_relay')['secret']['password'] }}"
    host: smtp.gmail.com
    port: 587
  authorized_networks:
    - 10.2.50.0/24
    - 10.2.51.0/24
    - 10.2.20.0/24
  