kea_dhcp:
  version: 2.4.1-3ubuntu0.1
  db:
    name: keadhcp
    username: keadhcp_user
    password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'postgresql/users')['secret']['keadhcp_user'] }}"
  dhcpconf:
    dns_servers: 
      - "{{ globvar.dns_servers[0] }}"
    search_domain: "{{ globvar.domains.internal }}"
    networks:
      - vlan10:
        id: 10
        subnet: 10.2.10.0/24
        pools:
          - "10.2.10.10 - 10.2.10.199"
        routers:
          - 10.2.10.1
      - vlan11:
        id: 11
        subnet: 10.2.11.0/24
        pools:
          - "10.2.11.10 - 10.2.11.199"
        routers:
          - 10.2.11.1
      - vlan20:
        id: 20
        subnet: 10.2.20.0/24
        pools:
          - "10.2.20.10 - 10.2.20.199"
        routers:
          - 10.2.20.1